### PR TITLE
add cuda support

### PR DESCRIPTION
**Pull request by spartanhaden**
Added CUDA support

timed moondream function 5 times before an after change and got the below average times
CPU 34.44s
CUDA 2.83s

~12x speedup

### CODE REVIEW

**Review by Yahatix — APPROVED** [review]

**Comment by vikhyat** [comment]
🙏🙏

**Comment by MNeMoNiCuZ** [comment]
How do I switch to/choose CUDA? The code in the project doesn't match what was submitted here as far as I can see. Was it changed again or moved to another location?

I would love to know how to trigger inference using CUDA instead of CPU.

**Comment by iamrohitanshu** [comment]
Hi @spartanhaden , I just git pulled this repo and am using it right now, but it seems to run on CPU still.
My GPU usage doesn't go up at all, but my CPU goes to 60% usage.
Has this commit of yours not integrated in the main somehow?
Do I need to do something else as well?

**Comment by MNeMoNiCuZ** [comment]
> Hi @spartanhaden , I just git pulled this repo and am using it right now, but it seems to run on CPU still. My GPU usage doesn't go up at all, but my CPU goes to 60% usage. Has this commit of yours not integrated in the main somehow? Do I need to do something else as well?

Did you install Pytorch properly? If it's not installed and active for the environment you launch this in, it won't work.
This was the problem I had with it. After this it worked right away and was super fast.

**Comment by iamrohitanshu** [comment]
@MNeMoNiCuZ I have torch-2.1.2 installed. It shows in the pip list.
I haven't made any environment for it separately, therefore just installed it globally I guess.
I have RTX 3060 with Windows 10, if that makes any difference.

EDIT: `torch.cuda.is_available()` is returning `False`. So there's something definitely wrong with the way I installed things. I'm looking into it right now. Thanks for the hint.

EDIT2: I created a venv, manually installed cuda in that, and it worked. Thanks!

**Comment by iamrohitanshu** [comment]
So, finally I managed to run it with cuda, but it takes around 5-6 GB of my VRAM, which I'd like to be free sometimes for other things.
Passing the `--cpu` flag isn't working for me. I do it like this:
`(venv) D:\moondream>py gradio_demo.py --cpu`
Am I doing it wrong? It still works on GPU, while showing this:
```
Using device: cuda
If you run into issues, pass the `--cpu` flag to this script.
```

**Pull request merged**
