### PR TITLE
Adding and updating the files for a gradio demo

### PR DESCRIPTION
**Pull request by yvrjsharma**
Hi, 
Kudos for this amazing project! I believe it would be great if the community can have an option to explore the Vision LLM through a web UI. To facilitate this, I have added a gradio_app.py file, included gradio in the requirements.txt file, and provided instructions in the readme for running the gradio demo.

This is how the webui would look -

image

image

### CODE REVIEW

**Comment by vikhyat** [comment]
Darn, wish I saw this before I reimplemented it :'( https://huggingface.co/spaces/vikhyatk/moondream1

Thanks a lot for the contribution, the UX looks a lot nicer than what I came up with. I'll take a look later and consolidate the two.

**Comment by yvrjsharma** [comment]
Brilliant! Thanks @vikhyat . Also your app on Spaces is amazing, I'll send some PRs your way over there as well.

**Comment by yvrjsharma** [comment]
Also, if anyone curious find their way to this thread, the Gradio app for the moondream project can be found on Spaces over here - https://huggingface.co/spaces/vikhyatk/moondream1

**Comment by yvrjsharma** [comment]
Sorry for the spam. Can you enable community contributions and pull requests on your space please? This would allow the community to use the space  just like a GitHub repository where they can request PRs to contribute/enhance to the demo?
image

**Comment by vikhyat** [comment]
On it, and thanks again for helping out!

**Pull request merged**
