### PR TITLE
Support for multi-round chat.

### PR DESCRIPTION
**Pull request by mazzzystar**
Hi thanks for your impressive work : )

I found that its speed is quite fast. Since it currently does not support multi-round dialogues, I tried to add this feature. I am not sure if my modification is correct, but I tested it myself and it seems to work.

```
>>> python sample.py --image assets/demo-2.jpg
Fetching 16 files: 100%|██████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 203360.19it/s]

> tell me what's in this picture
The image features a young woman sitting at a dining table, holding a large hamburger in her hands. She appears to be enjoying her meal, as the burger is almost as big as she is. There are a few other people in the scene, one on the left side of the image and two on the right side. They seem to be watching or engaging with the woman as she eats her meal.
> so why it's large
The hamburger is large because it is a specialty burger from a restaurant that is known for its large portions. This type of burger is popular among customers who want to try something different or who have a hearty appetite. The restaurant likely advertises their specialty burgers to attract customers who are looking for a unique and filling dining experience.
> where I can get
You can get this specialty hamburger at the restaurant shown in the image. The restaurant is known for serving large portions of their specialty burgers, which are popular among customers who want to try something different or who have a hearty appetite.
> why popular
The specialty hamburger is popular among customers because it is large, flavorful, and visually appealing. The restaurant has mastered the art of creating a delicious and satisfying burger that caters to different tastes and preferences. The size of the burger is a key factor that sets it apart from other burgers, making it a favorite among those who enjoy indulging in a hearty meal.
```

### CODE REVIEW

**Comment by mazzzystar** [comment]
Hi, I've resolved the conflict since you've updated to use `Stream` for response, and I've tested the results; they seem correct.

**Comment by vikhyat** [comment]
Thank you! The model was indeed trained to support it but I didn’t
implement it in the inference code. Will merge tomorrow morning.

**Comment by mazzzystar** [comment]
Great! Be sure to check the implementation of the prompt, as currently, I just use:
```
chat_history = "Question:" + question + "\n" + "Answer:" + answer + "\n\n" if answer else ""
```

It might work better if it aligns with the training instruction format, such as `user/assistant`.

**Comment by vikhyat** [comment]
🙏

**Pull request merged**
